apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nginx
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: example
    component: nginx
spec:
  selector:
    matchLabels:
      app: example
      component: nginx
  template:
    metadata:
      labels:
        app: example
        component: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
          - name: reloader-config
            mountPath: "/usr/share/nginx/html"
      volumes:
        - name: reloader-config
          configMap:
            name: reloader-config

