apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "use_ingress" "1" }}'
spec:
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: example-nginx
            servicePort: 80

