---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: reloader-reloader
  name: reloader-reloader-role
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - deployments
      - daemonsets
    verbs:
      - list
      - get
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: reloader-reloader
  name: reloader-reloader-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reloader-reloader-role
subjects:
  - kind: ServiceAccount
    name: reloader-reloader
    namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reloader-reloader
    group: com.stakater.platform
    provider: stakater
    version: v0.0.77
    
  name: reloader-reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader-reloader
  template:
    metadata:
      labels:
        app: reloader-reloader
        group: com.stakater.platform
        provider: stakater
        version: v0.0.77
        
    spec:
      containers:
      - image: "stakater/reloader:v0.0.77"
        imagePullPolicy: IfNotPresent
        name: reloader-reloader

        ports:
        - name: http
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
      securityContext: 
        runAsNonRoot: true
        runAsUser: 65534
        
      serviceAccountName: reloader-reloader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: reloader-reloader
  name: reloader-reloader

