apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multiprem
  namespace: '{{repl Namespace}}'
subjects:
- kind: ServiceAccount
  name: multiprem
  namespace: '{{repl Namespace}}'
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
