apiVersion: v1
kind: Secret
metadata:
  name: multiprem
  labels:
    app: multiprem
type: Opaque
data:
  postgres_database: repl{{ ConfigOption "postgres_database" | Base64Encode}}
  postgres_password: repl{{ ConfigOption "postgres_password" | Base64Encode}}
  postgres_username: repl{{ ConfigOption "postgres_username" | Base64Encode}}
