apiVersion: v1
kind: Service
metadata:
  name: multiprem-web
  labels:
    app: multiprem
    role: web
spec:
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: multiprem
    role: web
