apiVersion: v1
kind: Service
metadata:
  name: my-nodeport
spec:
  type: NodePort
  ports:
  - port: repl{{ ConfigOption "[[repl .nginx ]]" | ParseInt }}
    name: '{{repl ConfigOption "[[repl .nginx ]]" }}'