apiVersion: troubleshoot.replicated.com/v1beta1
kind: SupportBundle
metadata:
  name: amundsen-support-bundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=amundsen
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 30d
          maxLines: 10000
