apiVersion: schemas.schemahero.io/v1alpha3
kind: Table
metadata:
  name: users
spec:
  database: pg-consumer
  name: users
  schema:
    postgres:
      primaryKey: [id]
      columns:
        - name: id
          type: serial
        - name: name
          type: varchar(255)
        - name: email
          type: varchar(255)
