apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: ring-game
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=kubecon-game
        namespace: default
        limits:
          maxAge: 30d
          maxLines: 10000
    - exec:
        name: check-config
        collectorName: check-config
        selector:
          - app=file-check-pod
        namespace: default
        args:
        - stat
        - -c
        - "%a"
        - /etc/ring-game/config.txt
    - exec:
        name: check-restrain
        collectorName: check-restrain
        selector:
          - app=file-check-pod
        namespace: default
        args:
        - stat
        - -c
        - "%a"
        - /etc/ring-game/restraining-bolt.txt 
     
  analyzers:
    - textAnalyze:
        checkName: Config Check
        fileName: check-config/default/*/check-config-*.txt
        regex: '400'
        outcomes:
          - pass:
              message: Found Config File!!!
          - fail:
              message: Config file not found. Please check this [article](https://github.com/replicatedhq/kotsapps/blob/kc2021-ring-game/kubecon-2021-ring-game/content/solutions/easysolve.md)
    - textAnalyze:
        checkName: Restrain Check
        fileName: check-restrain/default/*/check-restrain-*.txt
        regex: '400'
        outcomes:
          - pass:
              message: Found Restraint File!!!
          - fail:
              message: Restrain file not found in /etc/ring-game/restraint-bolt.txt with 400 permissions.
    - textAnalyze:
        checkName: Service Check
        fileName: cluster-resources/services/default.json
        regex: '"name": "kotsadm"'
        outcomes:
          - pass:
              message: "kotsadm service found!"
          - fail:
              message: "Can't find kotsadm service"