apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: wordpress
spec:
  groups:
    - name: wordpress
      title: Wordpress Configuration
      items:
      - name: wordpress_username
        title: Wordpress Username
        type: text
        required: true
      - name: wordpress_password
        title: Wordpress Password
        type: password
        required: true
      - name: wordpress_firstname
        title: Wordpress User First Name
        type: text
        required: true
      - name: wordpress_lastname
        title: Wordpress User Last Name
        type: text
        required: true
      - name: wordpress_email
        title: Wordpress User Email
        type: text
        required: true
      - name: wordpress_blogname
        title: Wordpress Blog Name
        type: text
        required: true
      - name: wordpress_capacity
        title: Wordpress Capacity
        type: text
        default: "10Gi"
        hidden: true
        
    - name: database
      title: Database
      items:
        - name: mariadb_type
          help_text: Would you like to use an embedded mariadb instance, or connect to an external instance that you manage?
          type: select_one
          title: MariaDB
          default: embedded_mariadb
          items:
            - name: embedded_mariadb
              title: Embedded Mariadb
            - name: external_mariadb
              title: External MariaDB
        - name: embedded_mariadb_user
          hidden: true
          type: text
          value: "bn_wordpress"
        - name: embedded_mariadb_database
          hidden: true
          type: text
          value: "bitnami_wordpress"
        - name: embedded_mariadb_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: embedded_mariadb_root_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: embedded_mariadb_capacity
          hidden: true
          title: MariaDB Database Capacity
          type: text
          value: "8Gi"
        - name: embedded_mariadb_host
          hidden: true
          title: MariaDB Database Host
          type: text
          value: "server"
        - name: external_mariadb_host
          title: Postgres Host
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb"}}'
          type: text
          default: mariadb
        - name: external_mariadb_port
          title: MariaDB Port
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb"}}'
          type: text
          default: "3306"
        - name: external_mariadb_user
          title: MariaDB Username
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb"}}'
          type: text
          required: true
        - name: external_mariadb_password
          title: MariaDB Password
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb"}}'
          type: password
          required: true
        - name: external_mariadb_root_password
          title: MariaDB Root Password
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb"}}'
          type: password
          required: true
        - name: external_mariadb_database
          title: MariaDB Database Name
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb"}}'
          type: text
          default: mariadb
          required: true