apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: wordpress
spec:
  groups:
    - name: wordpress
      title: Wordpress Configuration
      items:
      - name: wordpress_username
        title: Wordpress Username
        type: text
        required: true
      - name: wordpress_password
        title: Wordpress Password
        type: password
        required: true
      - name: wordpress_firstname
        title: Wordpress User First Name
        type: text
        required: true
      - name: wordpress_lastname
        title: Wordpress User Last Name
        type: text
        required: true
      - name: wordpress_email
        title: Wordpress User Email
        type: text
        required: true
      - name: wordpress_blogname
        title: Wordpress Blog Name
        type: text
        required: true
      - name: wordpress_capacity
        title: Wordpress Capacity
        type: text
        default: "10Gi"
        hidden: true
        
    - name: database
      title: Database Options
      items:
        - name: mariadb_type
          type: select_one
          title: MariaDB
          default: embedded_mariadb
          items:
            - name: embedded_mariadb
              title: Embedded MariaDB
            - name: external_mariadb_inline
              title: External MariaDB
        - name: embedded_mariadb_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: embedded_mariadb_root_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: embedded_mariadb_capacity
          title: MariaDB Database Capacity (1Gi to 10Gi)
          type: text
          default: "8Gi"
        - name: external_mariadb_host
          title: MariaDB Host
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb_inline"}}'
          type: text
          default: mariadb
        - name: external_mariadb_port
          title: MariaDB Port
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb_inline"}}'
          type: text
          default: "3306"
        - name: external_mariadb_user
          title: MariaDB Username
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb_inline"}}'
          type: text
          required: true
        - name: external_mariadb_password
          title: MariaDB Password
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb_inline"}}'
          type: password
          required: true
        - name: external_mariadb_root_password
          title: MariaDB Root Password
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb_inline"}}'
          type: password
          required: true
        - name: external_mariadb_db
          title: MariaDB Database
          when: '{{repl ConfigOptionEquals "mariadb_type" "external_mariadb_inline"}}'
          type: text
          default: mariadb