apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mariadb
  labels:
    app: mariadb
    release: wordpress
type: Opaque
data:
  MARIADB_HOST: >-
    {{repl if ConfigOptionEquals "mariadb_type" "embedded_mariadb" }}
      {{repl Base64Encode "mariadb" }}
    {{repl else}}
      {{repl ConfigOption "external_mariadb_host" | Base64Encode }}
    {{repl end}}
  MARIADB_USER: >-
    {{repl if ConfigOptionEquals "mariadb_type" "embedded_mariadb" }}
      {{repl ConfigOption "embedded_mariadb_user" | Base64Encode }}
    {{repl else}}
      {{repl ConfigOption "external_mariadb_user" | Base64Encode }}
    {{repl end}}
  MARIADB_PASSWORD: >-
    {{repl if ConfigOptionEquals "mariadb_type" "embedded_mariadb" }}
      {{repl ConfigOption "embedded_mariadb_password" | Base64Encode }}
    {{repl else}}
      {{repl ConfigOption "external_mariadb_password" | Base64Encode }}
    {{repl end}}
  MARIADB_ROOT_PASSWORD: >-
    {{repl if ConfigOptionEquals "mariadb_type" "embedded_mariadb" }}
      {{repl ConfigOption "embedded_mariadb_root_password" | Base64Encode }}
    {{repl else}}
      {{repl ConfigOption "external_mariadb_root_password" | Base64Encode }}
    {{repl end}}
  MARIADB_DATABASE: >-
    {{repl if ConfigOptionEquals "mariadb_type" "embedded_mariadb" }}
      {{repl ConfigOption "embedded_mariadb_database" | Base64Encode }}
    {{repl else}}
      {{repl ConfigOption "external_mariadb_database" | Base64Encode }}
    {{repl end}}