apiVersion: v1
kind: Secret
metadata:
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "mariadb_type" "embedded_mariadb"}}'
  name: wordpress-mariadb
  labels:
    app: mariadb
    release: wordpress
type: Opaque
data:
  mariadb-password: '{{repl ConfigOption "embedded_mariadb_password" | Base64Encode}}'
  mariadb-root-password: '{{repl ConfigOption "embedded_mariadb_root_password" | Base64Encode}}'