apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb
  labels:
    app: mariadb
    component: master
    release: wordpress
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mariadb
    component: master
    release: wordpress
  type: ClusterIP