apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    release: wordpress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30080
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      nodePort: 30443
      protocol: TCP
      targetPort: https
  selector:
    app: wordpress
    release: wordpress