apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  labels:
    app: wordpress
    release: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{repl ConfigOption "wordpress_capacity"}}'