---
apiVersion: v1
kind: Secret
metadata:
  name: non-helm-b64-files
type: kubernetes.io/tls
data:
  tls.crt: repl{{ ConfigOptionData "ingress_tls_cert" | Base64Encode }}
  tls.crt.b64: repl{{ ConfigOption "ingress_tls_cert" }}
