apiVersion: v1
kind: Service
metadata:
  name: kubecon-game
  labels:
    app: kubecon-game
    component: nginx
  annotations:
    kots.io/when: "{{repl IsKurl}}"
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 8080
  selector:
    app: kubecon-game
    component: nginx
