apiVersion: v1
kind: Service
metadata:
  name: kubecon-game
  labels:
    app: kubecon-game
    component: nginx
  annotations:
    kots.io/when: "{{repl not IsKurl}}"
spec:
  type: ClusterIP
  ports:
  - port: 3000
  selector:
    app: kubecon-game
    component: nginx
