apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: helm-influx-config
spec:
  groups:
    - name: influx
      title: Influx
      description: Influx Configuration
      items:
        - name: admin_username
          title: Admin Username
          type: text
          default: 'admin'
        - name: admin_password
          title: Admin Password
          type: password
          default: 'admin'
