apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: collector-sample
spec:
  collectors:
    - logs:
        name: app-logs
        selector:
          - app=many-init-containers
        namespace: default
    - logs:
        name: failing-app-logs
        selector:
          - app=failing-init-container
        namespace: default
