apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - logs:
        name: app-logs
        selector:
          - app=many-init-containers
        namespace: tmp
    - logs:
        name: failing-app-logs
        selector:
          - app=failing-init-container
        namespace: tmp
