apiVersion: v1
kind: Service
metadata:
  name: gooddata
  labels:
    app: gooddata
    component: monolith
spec:
  type: ClusterIP
  ports:
  - port: 3000
  selector:
    app: gooddata
    component: monolith
