apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values-config-map
data:
  kots-values.yaml: |
    image:
      repository: {{repl if HasLocalRegistry }}{{repl LocalRegistryAddress}}{{repl else}}grafana{{repl end}}/grafana
    testFramework:
      enabled: {{repl if ConfigOptionEquals `enable_test_framework` `1`}}true{{repl else}}false{{repl end}}
    persistence:
      enabled: {{repl if ConfigOptionEquals `enable_persistence` `1`}}true{{repl else}}false{{repl end}}