apiVersion: troubleshoot.replicated.com/v1beta1
kind: SupportBundle
metadata:
  name: keycloak-support-bundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=keycloak
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 30d
          maxLines: 10000
