apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: es-data
  name: es-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
